version: 2
jobs:
  build:
    machine: true    
    steps:
      - checkout
      - run: 
          name: build docker image
          command: docker build --rm=false -t implementsio/dockerizer .
      - run: 
          name: login to hub.docker.com
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: push to hub.docker.com
          command: docker push implementsio/dockerizer